version: '2'

services:
  discourse:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      RAILS_ENV: 'production'
      DISCOURSE_DB_HOST: db
      DISCOURSE_DB_PORT: '5432'
      DISCOURSE_DB_NAME: 'root'
      DISCOURSE_DB_USERNAME: 'root'
      DISCOURSE_DB_PASSWORD: 'root'
      DISCOURSE_HOSTNAME: 'localhost'
      DISCOURSE_SMTP_ADDRESS: smtp.gmail.com
      DISCOURSE_SMTP_PORT: 587
      DISCOURSE_SMTP_USER_NAME: 'matheuzin@gmail.com'
      DISCOURSE_SMTP_PASSWORD: '19930113'
      DISCOURSE_DEVELOPER_EMAILS: 'matheus.souza.fernandes@gmail.com'
      DISCOURSE_REDIS_HOST: 'redis'
      DISCOURSE_REDIS_PORT: 6379
      DISCOURSE_RELATIVE_URL_ROOT: '/expressao'
      DISCOURSE_CONTACT_EMAIL: 'matheuzin@gmail.com'
      DISCOURSE_CONTACT_URL: 'localhost'
      DISCOURSE_NOTIFICATION_EMAIL: 'noreply@dicourse.org'
      DISCOURSE_LOGO_URL: '\/images\/d-logo-sketch.png'
      DISCOURSE_SMALL_LOGO_URL: '\/images\/d-logo-sketch-small.png'
      DISCOURSE_FAVICON_URL: '\/images\/default-favicon.ico'
      DISCOURSE_APPLE_TOUCH_ICON_URL: '\/images\/default-apple-touch-icon.png'
      DISCOURSE_SSO_URL: 'http:\/\/127.0.0.1:8000'
      DISCOURSE_SSO_SECRET: 'sso_secret'
      DISCOURSE_FORCE_HOSTNAME: ''

  sidekiq:
    build: .
    depends_on:
      - db
      - redis
    command: './start-sidekiq.sh'
    environment:
      RAILS_ENV: 'production'
      DISCOURSE_DB_HOST: db
      DISCOURSE_DB_PORT: '5432'
      DISCOURSE_DB_NAME: 'root'
      DISCOURSE_DB_USERNAME: 'root'
      DISCOURSE_DB_PASSWORD: 'root'
      DISCOURSE_HOSTNAME: 'localhost'
      DISCOURSE_SMTP_ADDRESS: smtp.gmail.com
      DISCOURSE_SMTP_PORT: 587
      DISCOURSE_SMTP_USER_NAME: 'matheuzin@gmail.com'
      DISCOURSE_SMTP_PASSWORD: '19930113'
      DISCOURSE_DEVELOPER_EMAILS: 'matheus.souza.fernandes@gmail.com'
      DISCOURSE_REDIS_HOST: 'redis'
      DISCOURSE_REDIS_PORT: 6379
      DISCOURSE_RELATIVE_URL_ROOT: '/expressao'
      DISCOURSE_CONTACT_EMAIL: 'matheuzin@gmail.com'
      DISCOURSE_CONTACT_URL: 'localhost'
      DISCOURSE_NOTIFICATION_EMAIL: 'noreply@dicourse.org'
      DISCOURSE_LOGO_URL: '\/images\/d-logo-sketch.png'
      DISCOURSE_SMALL_LOGO_URL: '\/images\/d-logo-sketch-small.png'
      DISCOURSE_FAVICON_URL: '\/images\/default-favicon.ico'
      DISCOURSE_APPLE_TOUCH_ICON_URL: '\/images\/default-apple-touch-icon.png'
      DISCOURSE_SSO_URL: 'http:\/\/127.0.0.1:8000'
      DISCOURSE_SSO_SECRET: 'sso_secret'
      DISCOURSE_FORCE_HOSTNAME: ''

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root

  redis:
    image: redis:alpine
